# This workflow synchronizes a github repository with the staging server
# In order to work properly, the following secrets need to be defined for the repo:
# HOST, PORT, USERNAME and PASSWORD
# Ping Thomas if you have any questions/issues

name: Sync to Staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            git -C /home/rggc/public_html/RGGC add .
            git -C /home/rggc/public_html/RGGC stash
            git -C /home/rggc/public_html/RGGC pull
            yarn --cwd /home/rggc/public_html/RGGC/wp-content/themes/rggc/ install
            yarn --cwd /home/rggc/public_html/RGGC/wp-content/themes/rggc/ build  
